### ISSUE TITLE
Version of BizTalk in registry

### ISSUE THREAD

**Issue by RobBowman** [MicrosoftDocs/biztalk-docs#411]
Re the page at: [https://docs.microsoft.com/en-us/biztalk/core/what-version-of-biztalk-server-do-i-have](https://docs.microsoft.com/en-us/biztalk/core/what-version-of-biztalk-server-do-i-have ), it seems advice to use the registry is flawed. I have successfully applied Feature Pack 3 / CU 5 to two different BizTalker servers. The "Product Version" value in the registry was not updated for either. However, the version displayed on Control Panel\Programs and Features does display the new version correctly.

**Comment by clineer** [comment]
I think this article was from before the feature pack model was started. Maybe create a PR documentation update which gives a little note that the instructions do not apply for feature packs? Let me know if you need me to create the PR.

**Comment by MandiOhlinger** [comment]
@RobBowman @clineer - It'd be great if we could get a PR with the proposed changes.

**Comment by clineer** [comment]
Mandi,
I will work on a PR when I get some time to confirm this.

Thanks,
Ben

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by dnsss90** [comment]
"SQL Server 2016 Standard supports only one single database in each SQL AlwaysOn AG. Since BizTalk uses many databases, SQL Server Enterprise edition is typically recommended." - what do you mean SQL Server 2016 only supports one single databse in each availability group? I'm sure you can have a lot of databases in a single availability group.

**Comment by ecfan** [comment]
Created work item and assigned to product team.
